name: CI/CD

on:
  push:
    branches:
    - '**'
  pull_request:
    types: [closed]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.context.outputs.should-publish }}
      current-version: ${{ steps.context.outputs.current-version }}
      release-type: ${{ steps.context.outputs.release-type }}
      cascading-release: ${{ steps.context.outputs.cascading-release }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet build
    - run: dotnet test
    - name: Establish context
      id: context
      uses: dolittle/establish-context-action@v2 # Replace with ./ if used withing dolittle/establish-context-action
      with:
        prerelease-branches: experimental,alpha,beta,rc

  release:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ needs.ci.outputs.should-publish == 'true' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Increment version
        id: increment-version
        uses: dolittle/increment-version-action@v2 # Replace with ./ if used withing dolittle/increment-version-action
        with:
          version: ${{ needs.ci.outputs.current-version }}
          release-type: ${{ needs.ci.outputs.release-type }}
      - name: Create GitHub Release
        uses: dolittle/github-release-action@v1 # Replace with ./ if used withing dolittle/github-release-action
        with:
          cascading-release: ${{ needs.ci.outputs.cascading-release }}
          version: ${{ steps.increment-version.outputs.next-version }}
      - name: Create packages
        run: dotnet pack --configuration Release -o Artifacts/NuGet /p:PackageVersion=${{ steps.increment-version.outputs.version }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: Push NuGet packages
        run: dotnet nuget push 'Artifacts/NuGet/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
